### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mindworker** [ory-am/ladon#11]
The **README** seems not up to date.

`guard.DefaultGuard` seems not in use anymore.

And following would throw compile errors:
`var pol := &policy.DefaultPolicy{`
`var guardian := new(guard.DefaultGuard)`
(var and := don't go together)

**Comment by arekkas** [comment]
Feel free to create a PR :) `guard.DefaultGuard` was renamed to `guard.Guard`

**Comment by mindworker** [comment]
https://github.com/ory-am/ladon/pull/12
