### ISSUE TITLE
Millions of subjects and resources

### ISSUE THREAD

**Issue by gchaincl** [ory-am/ladon#41]
I've been trying Ladon for a small set of subjects and resources and works great, but I'd like to know if it's intended to be used when the number of subjects and resources are around millions. Does this depend on the manager implementation?

**Comment by arekkas** [comment]
Yes, this is strongly dependent on the manager implementation

**Comment by gchaincl** [comment]
Thank you so much!

**Comment by arekkas** [comment]
You're welcome :)
